server:
  port: 3344

spring:
  application:
    name: cloud-config-center3344
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/wlOwn/springcloud-config.git
          search-paths:
            - springcloud-config
      label: master

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册消息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
  instance:
    instance-id: config-center #主机名修改
    prefer-ip-address: true #访问路径可显示IP地址

#    # 向服务端发送心跳的时间间隔，默认为30
#    lease-renewal-interval-in-seconds: 1
#    # eureka服务端在收到最后一次心跳后等待的时间上线，单位为秒(默认为90)，超时踢出
#    lease-expiration-duration-in-seconds: 2