server:
  port: 9527

spring:
  application:
    name: cloud-gateway9527

#    编码配置
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: CLOUD-PAYMENT-SERVICE # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/**
            # 断言，路径相匹配的进行路由
            #- After=2017-01-20T17:42:47.789-07:00[America/Denver]
            #- Before=2017-01-20T17:42:47.789-07:00[America/Denver]
            #- Cookie=username,zzyy
            #- Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性，并且值为正数
            #- Host=**.atguigu.com
            #- Method=GET
            #- Query=username, \d+ # 要有参数名username并且值还要是正整数才能路由
          # 过滤
          #filters:
          #  - AddRequestHeader=X-Request-red, blue

        - id: CLOUD-PAYMENT-SERVICE
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            Path=/payment/feign/** #断言,路径相匹配的进行路由

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册消息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
#      ,http://localhost:7002/eureka
  instance:
    instance-id: cloud-gateway9527 #主机名修改
    prefer-ip-address: true #访问路径可显示IP地址


#    # 向服务端发送心跳的时间间隔，默认为30
#    lease-renewal-interval-in-seconds: 1
#    # eureka服务端在收到最后一次心跳后等待的时间上线，单位为秒(默认为90)，超时踢出
#    lease-expiration-duration-in-seconds: 2