server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: false
    # false表示自己端就是注册中心,我的职责就是维护服务实例,并不需要检索服务
    fetch-registry: false
    # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
    # 单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    eviction-interval-timer-in-ms: 2000
      # 关闭自我保护模式，保证不可用服务及时踢出，最好开启保证高可用
    enable-self-preservation: false

  # 相互注册，注册到7002
#    service-url:
#      defaultZone: http://eureka7002.com:7002/eureka/