server:
  port: 8004

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2020?useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password:
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181


# MyBatis
mybatis:
  # 搜索指定包别名
#  typeAliasesPackage: com.tcy.springcloud.entities
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/*.xml
